<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "siteconfig"
 *
 * Auto generated by Extension Builder 2016-05-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MEDIENAGENTEN Site Configuration',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Arnd Messer',
	'author_email' => 'messer@medienagenten.de',
	'author_company' => 'Medienagenten',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);